********************************************************
********************************************************
*Author:			Alex Nur
*Topic:				Health/Exposure sd extraction
*Date created:		05/21/2025
*Date modified:		05/21/2025
********************************************************
********************************************************

*EXTRACT 1
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear

mi extract 1, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		

		
*EXTRACT 2
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 2, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 3
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 3, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 4
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 4, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 5
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 5, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 6
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 6, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		

		
*EXTRACT 7
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 7, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 8
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 8, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 9
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 9, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 10
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 10, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 11
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 11, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		

		
*EXTRACT 12
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 12, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 13
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 13, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 14
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 14, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 15
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 15, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 16
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 16, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		

		
*EXTRACT 17
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 17, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 18
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 18, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 19
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 19, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 20
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 20, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 21
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 21, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		

		
*EXTRACT 22
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 22, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
*EXTRACT 23
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 23, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 24
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 24, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
		
		
		
		
*EXTRACT 25
use "E:\Papers\Health and Waiver\Data\PtDImputed.dta", clear
		
mi extract 25, clear
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag == 1 & TRANSFER != .
		
sum SSITE SAGE SSGEND SPAEDUC SREL198 AGE_1_PRI_B4_BL SSROPRV ///
	SREL149 SDEM33 SDEM42 SCADPRE SDEM49 SROUT SPRINFL SSOCAP2 SNEISOC SMORDIS ///
	SMOTSUC SSUPAGG SAGGOFF SNEARPRO SINCOFF SDRUGOFF SIMPULS SFUTURE SMEDSEV ///
	SCONSID White Black Hispanic Other SCOMIN SSOCCST SEXPVIC SHEADIN ///
		if dvflag != 1 & TRANSFER != .
